### ISSUE TITLE
[Question] How to use custom RegisterProvider ?

### ISSUE THREAD

**Issue by Leibnizhu** [quarkiverse/quarkus-openapi-generator#108]
This plugin will add a `@RegisterProvider(CompositeAuthenticationProvider)` annotation at generated Api interface,   when authentication is defined in openapi spec.  

But in some case, we need custom RegisterProvider, e.g. logging. I wonder how to achieve it.

**Comment by ricardozanini** [comment]
@Leibnizhu there's no way to change the way we generate the API to add a custom `RegisterProviders`, but have you tried to extend the generated interface and add it there?

**Comment by Leibnizhu** [comment]
@ricardozanini Thx, good idea. it works for me

**Comment by ricardozanini** [comment]
@Leibnizhu, if you have the time, do you mind opening a PR to the README and adding a section there briefly explaining to users how to add custom `RegisterProvider`s? 🙇

**Comment by Leibnizhu** [comment]
@ricardozanini : i am glad to do that.
