### ISSUE TITLE
capability io.quarkus.rest.client provided by multiple providers

### ISSUE THREAD

**Issue by boun** [quarkiverse/quarkus-openapi-generator#110]
Hi,

I'd love to use your project in a project of mine, but migrated to resteasy-reactive, as that seemed to recommended by the quarkus documentation (https://quarkus.io/guides/resteasy Quote: *It is now recommended to use RESTEasy Reactive ....*). However that creates a conflict:

```
Please make sure there is only one provider of the following capabilities:
capability io.quarkus.rest.client is provided by:
  - io.quarkus:quarkus-rest-client-reactive::jar:2.9.2.Final
  - io.quarkus:quarkus-rest-client::jar:2.9.2.Final
```

I tried to exclude in gradle, hoping for a drop-in replacement:

```
    implementation ('io.quarkiverse.openapi.generator:quarkus-openapi-generator:0.9.0') {
        exclude group: 'io.quarkus', module: 'quarkus-rest-client'
    }
```

But that did not work as well. Any suggestions on how to proceed?

Thx
boun

**Comment by ricardozanini** [comment]
@boun, I believe we need to do this within the extension itself since there are changes in the deployment and runtime. You won't be able to change the dependencies this way. Additionally, I believe we might need to change the templates as well. I can work on this a few weeks from now.

**Comment by hbelmiro** [comment]
@boun I have started the migration to RESTEasy Reactive.
This is the tracking issue: https://github.com/quarkiverse/quarkus-openapi-generator/issues/150

**Comment by hbelmiro** [comment]
Closing as this is being tracked by https://github.com/quarkiverse/quarkus-openapi-generator/issues/150
