### ISSUE TITLE
Import generated-source files in target folder

### ISSUE THREAD

**Issue by svartkanin** [quarkiverse/quarkus-openapi-generator#117]
Hey everyone! 

This might be a silly question but how does one import the generated files such as `target/openapi/quarkus/clients_json/api/DefaultApi.java` in the actual source files located in `src/main/...`? 

when I try to inject the class with 

```
    @RestClient
    @Inject
    lateinit var defaultApi: DefaultApi
```

then the compilation fails because DefaultApi cannot be found.

I have tried specifying a different output folder as suggested here https://stackoverflow.com/questions/4121010/maven-cant-add-files-in-generated-sources-for-compilation-phase?rq=1 but that didn't work.

**Comment by ricardozanini** [comment]
Hi!

Quarkus automatically include the generated files into your classpath. You don't need to do anything.

Before adding the annotation to your files, generate them by running `mvn clean install`. Then in `target/generated-sources/openapi-json/<namespace>`, you should see everything generated for you.

The IDE should import these files to your classpath, so you can easily access them in your project.

**Comment by svartkanin** [comment]
@ricardozanini thanks for the reply. So what I did is create a file `src/main/openapi/clients.json` with 
```
{
  "openapi": "3.0.3",
  "info": {
    "title": "Simple API",
    "version": "1.0.0-SNAPSHOT"
  },
  "paths": {
    "/hello": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/bye": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

then I run
```
./mvnw package -pl cli -am -Dmaven.test.skip=true
```

which generated the file `target/generated-sources/open-api-json/org/openapi/quarkus/clients_json/api/DefaultApi.java ` with the content 

```
@Path("")
@RegisterRestClient( configKey="clients_json")
@GeneratedClass(value="clients.json", tag = "Default")
@ApplicationScoped
public interface DefaultApi {

    @GET
    @Path("/bye")
    @Produces({"text/plain"})
    @GeneratedMethod ("byeGet")
    public String byeGet(
    );


    @GET
    @Path("/hello")
    @Produces({"text/plain"})
    @GeneratedMethod ("helloGet")
    public String helloGet(
    );
}
```

So at this stage I would assume it is available to be used, but when using 
```
 @RestClient
 @Inject
 lateinit var defaultApi: DefaultApi
 ```
 
 It cannot be found 
 ```
 [ERROR] cli/src/main/kotlin/io/test/cli/commands/testCommand/Test.kt:[52,30] Unresolved reference: DefaultApi
 ```

**Comment by ricardozanini** [comment]
Yes, that should work. Are you using Kotlin, I'm assuming? So I think you must configure your build tooling to add the `target/generated-sources/open-api-json/` into your classpath.

@gastaldi, do you have any clue or experience with Kotlin + Quarkus generated files?

**Comment by gastaldi** [comment]
@ricardozanini No idea, but it seems to be a build tooling configuration as you said. Maybe @evanchooly knows about it

**Comment by evanchooly** [comment]
Generally the puffin that generates that code also updates the project model to include the generated source folder.  Otherwise you can use [this](http://www.mojohaus.org/build-helper-maven-plugin/usage.html) to manually add that folder.

**Comment by ricardozanini** [comment]
@evanchooly, I'm assuming the Quarkus plugin is already doing that, then? Because this works in Java.

**Comment by evanchooly** [comment]
I'm not familiar with that plugin honestly.   I would expect so. But it might be running afoul of the separate kotlin plug-in used to compile rather than the normal Java plug in. I'm on the road at the moment but can take a look in a few days unless @aloubyansky (I think...) knows better.

**Comment by aloubyansky** [comment]
We don't add sources directories to the Maven project in the Quarkus plugin. They are expected to be either added in the POM by the user or another plugin that is generating the sources.

**Comment by ricardozanini** [comment]
@aloubyansky, I thought our extension was already doing this since it works in the "vanilla" setup:

```xml
<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-maven-plugin</artifactId>
  <extensions>true</extensions>
  <executions>
    <execution>
      <goals>
        <goal>build</goal>
        <goal>generate-code</goal>
        <goal>generate-code-tests</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

The extension just delegates to Quarkus in build-time; the files are then generated in the right place:`target/generated-sources`. 

@svartkanin Can I take a look in your Kotlin setup?

**Comment by aloubyansky** [comment]
The question is in which phase the error happens? I suppose it could work in dev mode, assuming it can get passed the compilation phase in Maven. But `mvn compile` may fail because the compiler plugin may be missing the information about generated sources location. A reproducer would definitely help clarifying the issue.

**Comment by svartkanin** [comment]
Unfortunately I can't share any code around this as it's not a public repository

**Comment by aloubyansky** [comment]
@svartkanin could you perhaps create a very simple project that demonstrates the issue? That we could later also add to our testsuite.

**Comment by vladaman** [comment]
I do have same issue. Files are generated in target/ folder but Intellij does not include them automatically.

**Comment by aloubyansky** [comment]
@vladaman any chance you could share reproducer for us?

**Comment by vladaman** [comment]
@aloubyansky After few attempts it stared to work. I removed the maven module, added it again, executed ` mvn clean`, `mvn quarkus:generate-code` and restarted IntelliJ. After this it picked up the sources. It needs some specific steps to make it work. Not sure how to replicate this.

**Comment by aloubyansky** [comment]
It seems like because the directory containing the generated files didn't exist at the time of the original import and so it wasn't registered as a source dir. Not sure what we could do about it.
