### ISSUE TITLE
Multipart File Generation as InputStream

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-openapi-generator#118]
Current Multipart Generation is generating the call with a File object when an InputStream would be preferred.

**Current:**
```java
@FormParam("file")
@org.jboss.resteasy.annotations.providers.multipart.PartFilename("fileFile")
@org.jboss.resteasy.annotations.providers.multipart.PartType(MediaType.APPLICATION_OCTET_STREAM)
public File _file;
```

When ideally for more flexible client rather than requiring a File object requiring an InputStream so it can be streamed from say S3 or Azure Blob store.

**Wanted:**
```java
@FormParam("file")
@PartType(MediaType.APPLICATION_OCTET_STREAM)
public InputStream _file;
```

Full current example.
```java
    @PUT
    @Consumes({"multipart/form-data"})
    @Produces({"application/json"})
    @GeneratedMethod ("v2DocumentPut")
    public DocumentMetadata v2DocumentPut(
        @org.jboss.resteasy.annotations.providers.multipart.MultipartForm V2DocumentPutMultipartForm multipartForm
    );

    public static class V2DocumentPutMultipartForm {
        @FormParam("file")
        @org.jboss.resteasy.annotations.providers.multipart.PartFilename("fileFile")
        @org.jboss.resteasy.annotations.providers.multipart.PartType(MediaType.APPLICATION_OCTET_STREAM)
        public File _file;
        @FormParam("storagePath")
        @org.jboss.resteasy.annotations.providers.multipart.PartType(MediaType.TEXT_PLAIN)
        public String storagePath;
        @FormParam("storageContainer")
        @org.jboss.resteasy.annotations.providers.multipart.PartType(MediaType.TEXT_PLAIN)
        public String storageContainer;
    }
```

**Comment by ricardozanini** [comment]
@melloware, thanks for opening this issue.

Can you send a PR? This is a reasonably simple request. We can keep both options online with a codegen property. wdyt?

**Comment by melloware** [comment]
Yep let me work on that.  I may have a question on how to make it a switchable property.  But let me submit a PR for you to review.

**Comment by ricardozanini** [comment]
@melloware, I'll check in the codebase. These variables usually come from the bundle mapped by the openapi-generator library. Unfortunately, they are poorly documented, so we debug the `DefaultGenerator` class to find out.

@Orbifoldt, since you introduce this feature, can you please take a look?

**Comment by Orbifoldt** [comment]
Ok, so I see a few options:
1. We add the custom properties `typeMappings` and `importMappings` to this extension and forward their values to the corresponding properties part of that default code gen in the openapi generator. To achieve what we want we should set `typeMappings='File=InputStream'` and `importMappings='File=java.io.InputStream'`. (here `File` is the openapi type)
2. Same as 1., but use fully qualified name in the `typeMapping`, so `typeMappings='File=java.io.InputStream'`. Then you don't need to use the `importMappings`
3. Abstract option 1 away behind some ucstom property `fileDataType` whose value is either `File` or `InputStream`. Then we let our extension itself set the importmapping and typemapping when we instantiate the generator.

The nice thing about doing it as in option 1 (or 2) is that it can also be reused for other types, see for example this example: https://openapi-generator.tech/docs/usage/#type-mappings-and-import-mappings. However, it does require a bit more configuration for users. 

@ricardozanini what do you think is the way to go?

**Comment by melloware** [comment]
I like either but the simpler the better so `typeMappings='File=java.io.InputStream' I am good with.

**Comment by ricardozanini** [comment]
Thanks for the great summary, @Orbifoldt! I believe we can use the FQN, hence option 2.

**Comment by melloware** [comment]
@Orbifoldt any update on this?

**Comment by Orbifoldt** [comment]
I started working on this @melloware @ricardozanini , see #143

**Comment by melloware** [comment]
Closed with https://github.com/quarkiverse/quarkus-openapi-generator/pull/143

**Comment by melloware** [comment]
tested this today and it works perfectly!

**Comment by melloware** [comment]
Any change we can get a release I would like to use this plugin not in SNAPSHOT form???

**Comment by ricardozanini** [comment]
@melloware, we are releasing one after #158

**Comment by ricardozanini** [comment]
@melloware https://github.com/quarkiverse/quarkus-openapi-generator/releases/tag/0.12.0

Please, next time, don't let this rest too much time; we don't have a strict release schedule. This means that we can release any time the community needs.

**Comment by melloware** [comment]
Thank you !!!

**Comment by melloware** [comment]
@Orbifoldt I am seeing these warnings now though is this expected?  Everything is working properly.

I have
```
quarkus.openapi-generator.codegen.spec.documents_openapi_yml.type-mappings.File=InputStream
quarkus.openapi-generator.codegen.spec.documents_openapi_yml.import-mappings.File=java.io.InputStream
```

```
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.openapi-generator.codegen.spec.documents_openapi_yml.type-mappings.File" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.openapi-generator.codegen.spec.documents_openapi_yml.import-mappings.File" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

**Comment by Orbifoldt** [comment]
@melloware It seems to me a false-positive warning, I checked the unit/integration tests and there I see that warning there too (e.g. io.quarkiverse.openapi.generator.it.TypeAndImportMappingTest#canMapTypesAndImportToDifferentValues). I am still not 100% on how quarkus extensions should deal with config...

@ricardozanini Do you maybe know how to fix or suppress this warning? I did declare the config items in the SpecItemConfig class, and it doesn't complain about other items. Perhaps their type being `Optional<Map<String, String>>` is not correctly matched?

**Comment by ricardozanini** [comment]
Do you mind sending a PR? If I would guess, I'd say that not using `Optional` for maps is the way to go since a map can be empty.

**Comment by hbelmiro** [comment]
Yes, @ricardozanini is right. I've just tried here and Quarkus doesn't work with `Optional<Map<String, String>>`. If the config is absent, Quarkus converts it to an empty `Map`.

**Comment by Orbifoldt** [comment]
I fixed it in https://github.com/quarkiverse/quarkus-openapi-generator/pull/165
