### ISSUE TITLE
support openapi oneOf / anyOf

### ISSUE THREAD

**Issue by oliver-b-mazur-db** [quarkiverse/quarkus-openapi-generator#120]
The actual version of quarkus-openapi-generator is using version 5.4.0 of the openAPITools.
The openApiTools 5.4.0 does not support openapi oneOf and anyOf. Please update openApiTools to the last stable version 6.0.1 which supports oneOf / anyOf.

**Comment by ricardozanini** [comment]
@oliver-b-mazur-db it's on my plans to upgrade to 6.x, but since it's a major release, we might have to postpone a little bit to assess the impact.

**Comment by vladaman** [comment]
Does this apply to allOf ? It seems like generator is silently ignoring it.

**Comment by ricardozanini** [comment]
@vladaman, not sure. I have to look at the code. Suppose it's a feature that depends on 6.x, I'm afraid I can't add. But if it's there, we can add it to the templates.

**Comment by hbelmiro** [comment]
https://github.com/quarkiverse/quarkus-openapi-generator/pull/273 fixes this issue.

**Comment by gcomte** [comment]
I still have an issue with `oneOf`, using OpenAPI Generator - v2.2.1 

Specifically I'm trying to generate a model for the [BTCPay API](https://docs.btcpayserver.org/API/Greenfield/v1/swagger.json), but I get the following error:
```
cannot find symbol
symbol:   class OneOfstringobject
```

**Comment by gcomte** [comment]
@hbelmiro  Do you want me to add a new issue for this?

**Comment by hbelmiro** [comment]
@gcomte yes, please.
