### ISSUE TITLE
Change examples to a more use case/guides oriented documentation

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#151]
Currently, we have the examples documented as if they were all in the same project.
It would be better if they were written more oriented to use cases. Similar to what Quarkus has on its [guides](https://quarkus.io/guides/).

**Comment by ricardozanini** [comment]
@hbelmiro, feel free to open another issue to enhance the documentation of our examples. Also, we need to migrate to Quarkus Guides Antora style.
