### ISSUE TITLE
Possible to exclude from release build?

### ISSUE THREAD

**Issue by vladaman** [quarkiverse/quarkus-openapi-generator#173]
Quarkus OpenAPI generator is our biggest .jar dependency in production code. quarkus-openapi-generator-deployment adds about 5.8MB of package size. Since we deploy it on AWS Lambda it makes sense for us to optimize final package size.

Is there any way to remove this from release build? Is this .jar dependency required?

**Comment by hbelmiro** [comment]
quarkus-openapi-generator-deployment is not included in the production jar. How are you verifying this?
I've just created the jar for https://github.com/quarkiverse/quarkus-openapi-generator/tree/main/integration-tests/simple and it has only 643 bytes.

```bash
ls -lh target/quarkus-app/quarkus-run.jar                           
-rw-r--r-- 1 helber helber 643 nov  9 17:06 target/quarkus-app/quarkus-run.jar
```

**Comment by vladaman** [comment]
Thanks @hbelmiro for looking into this! It may be related to our specific use case in which we deploy code as AWS Lambda package.

```bash
mvn clean package -DskipTests
unzip -l target/function.zip | sort -rn | more
 86379869                     890 files
  7486416  2022-11-10 10:48   lib/org.hibernate.hibernate-core-5.6.10.Final.jar
  5560847  2022-11-10 10:48   lib/org.openapitools.openapi-generator-5.4.0.jar

ls -lh target/lib/io.quarkiverse.openapi*
-rw-rw-r-- 1 vlad vlad 33K Nov 10 10:48 target/lib/io.quarkiverse.openapi.generator.quarkus-openapi-generator-0.9.0.jar
-rw-rw-r-- 1 vlad vlad 42K Nov 10 10:48 target/lib/io.quarkiverse.openapi.generator.quarkus-openapi-generator-deployment-0.9.0.jar

ls -lh target/lib/org.openapi*
-rw-rw-r-- 1 vlad vlad 5.4M Nov 10 10:48 target/lib/org.openapitools.openapi-generator-5.4.0.jar
-rw-rw-r-- 1 vlad vlad  60K Nov 10 10:48 target/lib/org.openapitools.openapi-generator-core-5.4.0.jar
```

Our dependency:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-amazon-lambda-http</artifactId>
        </dependency>
```

**Comment by hbelmiro** [comment]
@vladaman as we can see in your output, the jar that uses 5.4M is the org.openapitools.openapi-generator-5.4.0.jar one. This is the underlying library, not quarkus-openapi-generator-deployment.

But anyway... I tried to create a reproducer here and in my example org.openapitools.openapi-generator-5.4.0.jar is not included in the generated zip.
Do you mind providing a reproducer?

**Comment by ricardozanini** [comment]
@vladaman, the `openapi-generator-5.4.0.jar` is only used for generating the OpenAPI code in build time. You don't need to ship this library in your production code. It seems to me that you somehow include the `*-deployment` jars to your package, which is not needed for runtime in any case AFAIK. That applies to any Quarkus plugin.
