### ISSUE TITLE
Use dynamic port where possible in tests that use WireMock

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#180]
There are a few tests that instantiate a `WireMockServer` with a fixed port, like: https://github.com/quarkiverse/quarkus-openapi-generator/blob/c4c13c6ad77928efee3fd69419c231b505e5b75d/integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/WiremockOpenWeather.java#L22

We should replace it with `new WireMockServer(WireMockConfiguration.wireMockConfig().dynamicPort())` always as possible to avoid flaky tests.

**Comment by dritoferro** [comment]
Hi @hbelmiro how are you ?

I was wondering if I could handle this one :)

Is it OK for you?

**Comment by ricardozanini** [comment]
Hi @dritoferro fell free to take it and send a PR to the repo. :)
Thanks!!
