### ISSUE TITLE
Mapping DateTime to Instant is ignored

### ISSUE THREAD

**Issue by mike-hampton-float** [quarkiverse/quarkus-openapi-generator#181]
Using a mapping to have the openapi `DateTime` map to `java.time.Instant` is ignored.  The type generated is still `java.time.OffsetDateTime`

The following repo illustrates the issue and allows it to be reproduced easily:
[https://github.com/mike-hampton-float/example-quarkus-api](https://github.com/mike-hampton-float/example-quarkus-api)

**Comment by ricardozanini** [comment]
I think this is a limitation of the inner generator:

> (Note that you won't be able to change all types as some are hardcoded in the generator, e.g. the OAS type DateTime.)

See: https://github.com/quarkiverse/quarkus-openapi-generator#type-and-import-mappings

Although I believe it is doable to take a look at the issue to see what can we do about it.

**Comment by ricardozanini** [comment]
cc @Orbifoldt @melloware

**Comment by melloware** [comment]
Have you tried.

```
quarkus.openapi-generator.codegen.spec.openapi_yaml.import-mappings.Instant=java.time.Instant
quarkus.openapi-generator.codegen.spec.openapi_yaml.type-mappings.OffsetDateTime=Instant
```

**Comment by mike-hampton-float** [comment]
Thanks you for the idea @melloware .  That did not work, it appears the import-mappings is ignored.
But it _did_ change the type of the variable.  So I tried

```
quarkus.openapi-generator.codegen.spec.openapi_yaml.type-mappings.OffsetDateTime=java.time.Instant
```

And it worked!  It places the fully qualified name in the variable, but that is ok. This is a good workaround, but I still see this as a bug.

**Comment by melloware** [comment]
nice yes i thought something looked off there!

**Comment by melloware** [comment]
OK so i think its your misunderstanding.  This is mapping Java Type to Java Type and you were supposing it was mapping OpenAPI type to Java Type.

So there is no `DateTime` in Java only OffSetDateTime, ZonedDateTime etc.  So its not a bug i think its just a misunderstanding.

**Comment by mike-hampton-float** [comment]
In another (much more complex) project, I have the following mapping: 
```
quarkus.openapi-generator.codegen.spec.openapi_yaml.type-mappings.Money=com.setscale.common.api.model.Money
quarkus.openapi-generator.codegen.spec.openapi_yaml.type-mappings.Currency=com.setscale.common.api.model.Currency
```
Where the openapi file has the type specified as 'Money' which is defined in the openapi file, but we reset the definition to a common data model.   This works.

We also do the same type of mapping when generating the server using `org.openapitools:openapi-generator-maven-plugin` 
```
                            <typeMappings>
                                <typeMapping>DateTime=Instant</typeMapping>
                                <typeMapping>Date=LocalDate</typeMapping>
                                <typeMapping>Money=com.setscale.common.api.model.Money</typeMapping>
                                <typeMapping>Currency=com.setscale.common.api.model.Currency</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>Instant=java.time.Instant</importMapping>
                                <importMapping>LocalDate=java.time.LocalDate</importMapping>
                            </importMappings>
```
There appears to be an inconsistency here.

**Comment by mike-hampton-float** [comment]
[This](https://github.com/mike-hampton-float/example-quarkus-api/blob/main/spec/openapi.yaml) is an example of the openapi.  The repo it is in does not include the custom mappings for the types (`CustomThing`, `CustomEnum`), but the openapi has the same structure.

**Comment by ricardozanini** [comment]
Which version of OpenAPI Generator Maven plugin are you using?

**Comment by mike-hampton-float** [comment]
6.2.0

**Comment by Orbifoldt** [comment]
Just tested it, by commenting out this line https://github.com/quarkiverse/quarkus-openapi-generator/blob/c46cee4c4d2cff785278dc30700c6537164b545b/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java#L28 and then setting
```java
                .withTypeMappings(Map.of("DateTime", "Instant"))
                .withImportMappings(Map.of("Instant", "java.time.Instant"))
```
it uses Instant for every field of oas type "DateTime" and adds the import

**Comment by ricardozanini** [comment]
@Orbifoldt can't we override or change the order? Or even send a PR to the OpenAPI Generator upstream?

**Comment by Orbifoldt** [comment]
@ricardozanini I am not sure if we can change the order, perhaps if we override the generate  or some other method of the generator and in there apply the user's mappings? 
@mike-hampton-float Do you maybe know what happens if in the maven plugin you both set dateLibrary to java8 and try to override the type mappings? 

Alternatively, we could perhaps remove the ` this.setDateLibrary(JavaClientCodegen.JAVA8_MODE)` line, and instead provide some default mappings that have the same effect (I am hoping that this `setDateLibrary` method is just shorthand for applying several mappings). Then any mappings provided by our users could override those default ones if they want?

**Comment by ricardozanini** [comment]
> and instead provide some default mappings that have the same effect

That's what I was thinking too.

**Comment by Orbifoldt** [comment]
I suddenly had some inspiration 😄 This PR should allow mapping of dates and datetimes: https://github.com/quarkiverse/quarkus-openapi-generator/pull/182
