### ISSUE TITLE
Fix import order

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#183]
There are files with imports in the wrong order. This causes changes in these files when we run `mvn verify`, since this goal fixes the order of the imports.

**Comment by ricardozanini** [comment]
I think we can add a step to our CI to verify if the developer has run it locally.

**Comment by hbelmiro** [comment]
> I think we can add a step to our CI to verify if the developer has run it locally.

I've created https://github.com/quarkiverse/quarkus-openapi-generator/issues/188 to track that.
