### ISSUE TITLE
Problem with enum array

### ISSUE THREAD

**Issue by namho123** [quarkiverse/quarkus-openapi-generator#205]
We had a problem with this swagger:  https://www.chatwoot.com/developers/swagger.json . Please check it!

**Comment by ricardozanini** [comment]
Hi! Thanks for opening this issue. Can you elaborate a bit more? Maybe share a reproducer and describe precisely what problem you are having.

Thanks!

**Comment by namho123** [comment]
It happended with format like this:
` "subscriptions": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "conversation_created",
              "conversation_status_changed",
              "conversation_updated",
              "message_created",
              "message_updated",
              "webwidget_triggered"
            ]
          },
          "description": "The list of subscribed events"
        },`

**Comment by ricardozanini** [comment]
I'm sorry, but I'm failing to understand your problem. Do you have a project where I can take a look and build locally?

**Comment by namho123** [comment]
Step by step to reproduce:
1. Generate project quarkus create app com.jiohealth:jio-chat-service --extension="quarkus-openapi-generator,quarkus-config-yaml" --gradle-kotlin-dsl --java=17
2. Create openapi folder in source, then copy https://www.chatwoot.com/developers/swagger.json into this directory
3. Run ./gradlew build , then check the errors.

**Comment by hbelmiro** [comment]
@namho123 I managed to reproduce the errors. I'll try to work on a fix in the next few days. 
Thank you for reporting.
