### ISSUE TITLE
Migrate README.md to quarkiverse-docs

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#213]
Instead of keeping our documentation in the README file, we should migrate it to Asciidoc and publish it in the Quarkiverse Documentation: https://quarkiverse.github.io/quarkiverse-docs/index/index/index.html.

It will help maintain it across the different versions and also with SEO.

See how to do it: https://github.com/quarkiverse/quarkiverse/wiki#documenting-your-extension

**Comment by TheJavaGuy** [comment]
@ricardozanini @hbelmiro If this is still needed maybe I can take a look.

**Comment by hbelmiro** [comment]
Yes. It's still needed, but I don't know if you have enough privileges.
@ricardozanini Do you know if he needs to be in the Quarkiverse organization to work on this?

**Comment by ricardozanini** [comment]
@TheJavaGuy @hbelmiro we do not require any special privileges, just migrate the README to the [docs](https://github.com/quarkiverse/quarkus-openapi-generator/tree/main/docs) directory and open a PR here. Thank you very much @TheJavaGuy. This would be a must for the community. :)

**Comment by TheJavaGuy** [comment]
Hey @hbelmiro @ricardozanini just to say that I didn't forget about this one, just I've been busy with fixing asciidoc errors in other extensions. But that should be done soon so I'll get back to this issue.
