### ISSUE TITLE
Mandatory OIDC auth dependency in 1.2.0 

### ISSUE THREAD

**Issue by tibersept** [quarkiverse/quarkus-openapi-generator#250]
Just updated to version 1.2.0 and noticed that an OIDC/OAuth Authentication Provider is generated even though neither the spec nor the configuration list/require an OIDC authentication.

This forces projects relying on `quarkus-openapi-generator` to always include `quarkus-oidc-client-filter`. 

Is there a way to avoid generating the OIDC/OAuth Auth Provider and thus the Quarkus OIDC dependency?

**Comment by hbelmiro** [comment]
@tibersept could you share a reproducer?

**Comment by hbelmiro** [comment]
This was probably fixed by https://github.com/quarkiverse/quarkus-openapi-generator/pull/249.
If it's easier for you than providing a reproducer, you can build the `quarkus2` branch locally and check if the issue was fixed.

**Comment by tibersept** [comment]
Thanks for the quick reply. Yes, I can confirm that 75e443e87579afd... in `quarkus2` fixes the issue. What forced the OIDC dependency was the fixed generation of the `SupportingFile`, which has been removed in the commit.

**Comment by hbelmiro** [comment]
Thank you @tibersept.

@ricardozanini can you release a new version, please?
