### ISSUE TITLE
Replace @JsonIgnoreProperties(ignoreUnknown = true) by @JsonAnySetter to allow fine tuned Serialization of unmapped fields

### ISSUE THREAD

**Issue by dgautier** [quarkiverse/quarkus-openapi-generator#280]
Hi,

I have a case when some properties can't be described in open api schema and as all model classes are annotated by default with @JsonIgnoreProperties(ignoreUnknown = true), i can't find a way to deserialize it properly.

An improvement would be to replace this by a Map annotated with @JsonAnySetter.

Let me know if you need further details or if you have any other idea to solve this.

**Comment by ricardozanini** [comment]
Hi @dgautier! Thank you for sharing this use case. Can you share your openapi file? Why the properties can't be described there? I'm just trying to have a better perspective of this use case.
