### ISSUE TITLE
Support for OpenApi Normalizer options

### ISSUE THREAD

**Issue by bpasson** [quarkiverse/quarkus-openapi-generator#319]
I'm dealing with schema's that use allOf as a parent relation. To get proper code generated I need to specify OpenApi Normalizer options, more specifically REF_AS_PARENT_IN_ALLOF=true. How can I achieve this?

**Comment by ricardozanini** [comment]
Hi! We are adding a few properties from the inner generator as they are requested for specific use cases. Can you please share a reproducer (your openapi or an excerpt), so we can implement this feature and add a test case to validate it?

**Comment by bpasson** [comment]
Sure, I will add a reproducer and open 2 PRs. One for Quarkus 2 and one for Quarkus 3. Just have a look at the PRs to see if this is something you want to support in the way I implemented it.

**Comment by bpasson** [comment]
If you use the Open API spec below, the Primate type is missing the Mammal properties, but has the Animal properties. To make it work the REF_AS_PARENT_IN_ALLOF=true Open API Normalizer option has to be set. This normalized the all of to a parent child relation.  One can argue this is a workaround.

I think the OpenAPI tools itself are buggy, as the inner domain object which is used for generating code, lists the Mammal interface for Primate, but forgets to aggregate the properties. It only aggregates the properties from Animal.

Never the less, it should still be possible to specify Open API Normalizer options in my opinion.

```
openapi: 3.0.2
info:
  title: Animals - OpenAPI 3.0
  version: 1.0.5
servers:
  - url: /api/v3
tags:
  - name: primate
    description: Everything about Primates
paths:
  /primate/{id}:
    get:
      tags:
        - primate
      summary: Find primate by ID
      description: Returns a single primate
      operationId: getPrimateById
      parameters:
        - name: id
          in: path
          description: ID of primate to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Primate'
        '400':
          description: Invalid ID supplied
        '404':
          description: Primate not found
components:
  schemas:
    Animal:
      type: object
      properties:
        born:
          type: string
          example: '2023-04-26T09:34:26.184Z'
        deceased:
          type: string
          example: '2023-04-30T17:41:11.154Z'
      xml:
        name: animal
    Mammal:
      type: object
      allOf:
        - $ref: '#/components/schemas/Animal'
      properties:
        gender:
          type: string
          enum:
            - female
            - male
      xml:
        name: mammal
    Primate:
      required:
        - name
      type: object
      allOf:
        - $ref: '#/components/schemas/Mammal'
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: jane doe
      xml:
        name: primate
```
