### ISSUE TITLE
Adding @QueryParam to POJO fields does not work with POST/PUT/PATCH using quarkus-rest-client-reactive-jackson

### ISSUE THREAD

**Issue by magori** [quarkiverse/quarkus-openapi-generator#357]
In the last version [2.2.5](https://github.com/hbelmiro/quarkus-openapi-generator/blob/347f02861e35e3aa9e863bf93aa3f81106dc3f6b/deployment/src/main/resources/templates/pojo.qute#L52) the QueryParam annotation is added on the fields.
But now when we execute a PUT with the rest-client-reactive the body is empty. 

LOG with @QueryParam on field name
_ 2023-06-06 11:30:20,588 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-2) Request: PUT http://localhost:8080/api/v1/project?name=Groupe1%2Fprojettest Headers[Accept=application/json Content-Length=0 User-Agent=Resteasy Reactive Client X-Api-Key=xxx], Empty body_

LOG without @QueryParam on field name
_2023-06-06 11:35:03,264 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-5) Request: PUT http://localhost:8080/api/v1/project Headers[Accept=application/json Content-Type=application/json User-Agent=Resteasy Reactive Client X-Api-Key=xxx content-length=29], Body:
{"name":"Groupe1/projettest"}_

Is it possible to deactivate/delete this annotation? 

For information we use Kotlin for the project

**Comment by ricardozanini** [comment]
Hi! Thanks for reporting it. Can you please share an OpenAPI model in which this annotation is wrongly generated?

**Comment by jasmdk** [comment]
Any spec where which has a requestBody will generate pojos where each property has the QueryParam annotation, and when invoking the request, all properties are added as query parameters to the URL and leaves the body empty

**Comment by ricardozanini** [comment]
I asked one because it will make my life easier to fix this bug as soon as possible. Thanks for the information anyway, I'll take care of it once I have the time.

**Comment by frederikb** [comment]
> I asked one because it will make my life easier to fix this bug as soon as possible. Thanks for the information anyway, I'll take care of it once I have the time.

Hi @ricardozanini: I created a PR which enhances the BeanParam integration test with a failing case. See #361 .

Most interestingly the test only fails if run against the `resteasy-reactive` Maven profile. However in my opinion the fact that RESTEasy Classic executes the expected request is perhaps more of an unexpected side-effect or bug and not by spec.

Thanks for looking into it!

**Comment by magori** [comment]
Hi, here is file ([dependency_track.zip](https://github.com/quarkiverse/quarkus-openapi-generator/files/11749304/dependency_track.zip)) we used, the probeme wase with thes class ProjectApi and the function createProject()  (`projectApi.createProject(project)`)

**Comment by ricardozanini** [comment]
@magori can I ask you to test with @frederikb's PR?

**Comment by frederikb** [comment]
Just to clarify: I did not contribute a fix with my PR. It only adds an additional test case which showcases the problem discussed in this ticket. 

Perhaps @hbelmiro can share some insights because I think this regression (IMO) is linked to #313 .

**Comment by ricardozanini** [comment]
@frederikb sure thing, I thought you added a fix since I didn't see the PR. I was on mobile. Thank you anyway, the contribution is valuable to help us fix it. Yes, it's a regression he introduced in a previous PR. I'll fix it tomorrow.

**Comment by magori** [comment]
When the fix is donne I will test the PR with pleasure.

**Comment by hbelmiro** [comment]
I'm looking into this. I couldn't find a way to make it work for both (body and query) kinds of params.
I opened [this issue](https://github.com/quarkusio/quarkus/issues/34143) in Quarkus asking for help.

**Comment by ricardozanini** [comment]
@hbelmiro couldn't we handle it on our side and avoid generating code that should be in the Body in the Query instead?

**Comment by hbelmiro** [comment]
@ricardozanini the change that causes the issue aims to solve precisely that. We were sending all in the body, even when we should be sending in the query. See the comment that originated the change: https://github.com/quarkusio/quarkus/issues/25370#issuecomment-1118284104

**Comment by hbelmiro** [comment]
Status report:
[The Quarkus team answered me on how to solve this use-case](https://github.com/quarkusio/quarkus/issues/34143#issuecomment-1598686426). However, I didn't have time to implement the fix so far. I hope to do this by the end of this week.
If anyone else wants to work on the fix right now, I'd be happy to help with the review.

**Comment by lordvlad** [comment]
@hbelmiro I tested your fix and unfortunately I don't see any difference in the output. I still see `QueryParam` annotations where they shouldn't be.

Trying to decipher the discussion here https://github.com/quarkusio/quarkus/issues/25370#issuecomment-1118284104 and https://github.com/quarkiverse/quarkus-openapi-generator/issues/59, I think the implementation was incomplete.

The generator should _only_ generate @BeanParam and @QueryParam annotations if the model is found in `parameters`, not in `requestBody`. E.g. in this line, it should check for `m.isBeanParam` or something https://github.com/quarkiverse/quarkus-openapi-generator/pull/313/files#diff-9e0f8b0b96cca99190af0732f4e919039f3c7866936baa301be9c6b1d00fccd8R51.

**Comment by lordvlad** [comment]
#385 fixes our issues!

**Comment by magori** [comment]
I tested the fix and everything is OK all the tests passed, thanks for the work.
