### ISSUE TITLE
Allow custom annotations on api types

### ISSUE THREAD

**Issue by lordvlad** [quarkiverse/quarkus-openapi-generator#388]
Analogous to `additional-model-type-annotations`, there should be an `additional-api-type-annotations` for cases when `custom-register-providers` does not suffice.

Example: Using quarkus oidc client, we can add an `@NamedOidcClient("foobar")` annotation to bind an oidc client to an rest interface. The current workaround involves creating a custom `FooBarOidcClientRequestReactiveFilter` that derives from `OidcClientRequestReactiveFilter`, and adding that via `custom-register-providers`. It would be nicer to just add `@NamedOidcClient("foobar")` in the generator config in `application.properties`.

```
quarkus.openapi-generator.codegen.spec.foobar.additional-api-type-annotatoins=@NamedOidcClient("foobar")
```

**Comment by ricardozanini** [comment]
Too many custom annotations use case. We should look for a way to give the template to users or be more pragmatic regarding customization.

**Comment by lordvlad** [comment]
With `additional-api-type-annotations`, you could replace some others, like authorization and header propagation, no?

**Comment by hbelmiro** [comment]
Fixed by: https://github.com/quarkiverse/quarkus-openapi-generator/pull/431
