### ISSUE TITLE
Document configuration Properties in the normal quarkus format? 

### ISSUE THREAD

**Issue by matter-it-does** [quarkiverse/quarkus-openapi-generator#389]
Are the configuration properties documented in a format similar to the following?

https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.connect-timeout

Currently I'm digging through tests and https://github.com/quarkiverse/quarkus-openapi-generator/blob/cbadd86c0fa01fa3945122e36f96dbe9520a145b/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java#L23

**Comment by matter-it-does** [comment]
I couldn't find a simple list and had to dig through the code. Any format is fine as long as it has all the key values.

**Comment by hbelmiro** [comment]
As I mentioned in my previous comment, there's an [issue](https://github.com/quarkiverse/quarkus-openapi-generator/issues/57) for that in our backlog.
If you have the time and would like to contribute, I'll be happy to help with the review.
