### ISSUE TITLE
Custom header propagation without security

### ISSUE THREAD

**Issue by michalsomora** [quarkiverse/quarkus-openapi-generator#394]
Hi,

In our applications we need to propagate custom header (identityToken from keycloak) passed from client (angular-ui) through bff to all other backend services. 

We deliver this feature with combination of @RegisterClientHeaders, "org.eclipse.microprofile.rest.client.propagateHeaders=token-name" property and client-headers-factory (#365), see more here https://quarkus.io/guides/rest-client#default-header-factory
But we found out that this approach has its limit:

@RegisterClientHeaders annotation is generated on api class only if the swagger api defines any kind of auth method (http, apiKey, oauth etc).  @RegisterProvider(CompositeAuthenticationProvider.class) is always generated together athough in our case its not needed at all. We dont need to handle it in any way, just want to pass it to any downstream service.
But there is no way to generate @RegisterClientHeaders on api class without @RegisterProvider(CompositeAuthenticationProvider.class).

**Goal**
1. Have an option to add @RegisterClientHeaders to implement simple headers propagation
2. Define own authentication provider

**Solution**
1. Add option to define own additional api annotation as requested here #388 
2. Add option to disable CompositeAuthenticationProvider generation and registration to rest api

Example of the configuration might look like:
quarkus.openapi-generator.codegen.spec.my_openapi_yaml.disable-auth-generation=true
quarkus.openapi-generator.codegen.spec.my_openapi_yaml.custom-register-providers=TopSecureAuthenticationProvider
quarkus.openapi-generator.codegen.spec.my_openapi_yaml.additional-api-annotation=@RegisterClientHeaders

and the result would be:
@RegisterProvider(TopSecureAuthenticationProvider.class)
@RegisterClientHeaders

First 2 options could be combined to one line with same result so if custom-auth-provider is provided plugin would not generate anything reg. authorization
quarkus.openapi-generator.codegen.spec.my_openapi_yaml.custom-auth-provider=TopSecureAuthenticationProvider

I believe this options will bring a lot of freedom to eveybody

Thanks for any feedback in advance.

**Comment by ricardozanini** [comment]
This is interesting, but I think we need to review this use case and merge it with the other one we have about adding custom registration. They are kind of entwined, so let's think about the usability of the library to avoid mixing these use cases. Maybe disabling everything and allowing custom providers should be the way to go.

If we decided this way, we might break the compatibility, hence we have to have a fallback under the hood.

**Comment by laurentperez** [comment]
Isn't https://github.com/quarkiverse/quarkus-openapi-generator#custom-register-providers-for-generated-api the "raw" solution @michalsomora ?
 
as in "Maybe disabling everything and allowing custom providers should be the way to go" from the idea above.

your provider may have access to ClientRequestContext, if you then do a programmatic lookup of the org.eclipse.microprofile.rest.client.propagateHeaders application.properties token name you might be able to "augment" the HTTP request/response

(unsure, just an idea so that compatibility may be safe)

**Comment by michalsomora** [comment]
Hi @laurentperez i think your solution might work but i would appreciate more robust solution than such workarounds
If lib suports additional annotations for models, why there should not be the same support for apis?

Biggest problem from my point of view is how to solve backward compatibility if we support "disable everything" but thats something i would really love to have. Lib should provide enough freedom for everybody to defines its own security behaviour (or any other) and no default implementation should be forced to use. Or at least there should be elegant way to overwrite everything

**Comment by michalsomora** [comment]
@ricardozanini i partially agree with you, spec should be source of truth but in reality its not always like that. In our project we get specs from different teams with different level of quality. Of course we could adjust them to make them perfect but specs evolve during the time, new versions are created and we would need to apply the same adjustments every time.
Being able to disable default security annoation and to define its own custom authorization will be more than welcome
I can help with implementing the solution but please find agreement soon how to proceed with #304 #388

**Comment by ricardozanini** [comment]
We can close those issues if we enable custom sec annotations.

**Comment by michalsomora** [comment]
Ok please let me know if i can somehow support this change, i would appreciate having this done asap. its blocking our migration of our project to quarkus 2
thanks

**Comment by hbelmiro** [comment]
Hi @michalsomora.
If you know how to implement it, go ahead.
And feel free to ask any questions.

**Comment by michalsomora** [comment]
Hi @hbelmiro 
I think i have an idea but i would like to first create a plan what to do before starting

1. introduce new config enable-security-generation with default value true
2. if false, no default security classes and annotation will be generated (RegisterProvider, CompositeAuthenticationProvider, AuthenticationPropagationHeadersFactory)
3. Implement additional-api-type-annotations configuration
4. Optional - remove custom-register-providers and client-headers-factory config since same behaviour can be achieved with new configs in more convenient way
Thats i think good for start, let me know what do you think about this plan

**Comment by ricardozanini** [comment]
We should have the 4th step too @michalsomora. It shouldn't be optional. The goal is to simplify this use case and avoid too many configs to achieve the same thing. Good plan! Many thanks!!

**Comment by hbelmiro** [comment]
Fixed by: https://github.com/quarkiverse/quarkus-openapi-generator/pull/431
