### ISSUE TITLE
Return Response for individual Operation doesn't seem to work

### ISSUE THREAD

**Issue by mzellho** [quarkiverse/quarkus-openapi-generator#424]
Please see my [comment](https://github.com/quarkiverse/quarkus-openapi-generator/pull/386#issuecomment-1655446766) in #386.

**Comment by hbelmiro** [comment]
@mzellho it seems to be working correctly.
I sent a [PR to test it](https://github.com/quarkiverse/quarkus-openapi-generator/pull/425).

**Comment by mzellho** [comment]
Thank you, @hbelmiro, I briefly compared your spec and application.properties to mine and couldn't spot any differences right now. I'll clone your PR and see if I can find out more. Thanks, again, for your time and the new test cases!

**Comment by mzellho** [comment]
Hmmm...I think I spotted the difference, @hbelmiro: In `testReturnResponseFalseVoid` you are asserting that the method should return `void` and that's either the bug or the feature. I would have thought that this test would assert `Response` instead of `void`.

I understood the feature in a way that it would also return `Response`, regardless of the state of `return-response`, so it would allow having typed Responses for all the operations featuring a response but also return `Response` in case the operation returns a 204, so Headers, Cookies, etc. can be evaluated.

What do you think?

**Comment by hbelmiro** [comment]
But that's exactly what `return-response` is intended for.
If you want to return `Response` instead of `void`, set `return-response = true`.

**Comment by mzellho** [comment]
Well, `return-response` is for ALL operations and my spec holds several operations, with one being void, and for all the others I want my typed Responses.

I must have misunderstood the feature, I'm afraid.

But okay, I can also take the response and deserialize manually. However, that would be a nice thing to have, maybe I'll prepare a PR that makes use of the vendor extension I mentioned in #386.

**Comment by lordvlad** [comment]
My intention in #386 was to return Response instead of void if no return type was specified and return-response was default (`false`). Exactly what @mzellho was writing.

Obviously, I should've adjusted the tests as well.

What's weird to me is that where I was using it, the return types seemed to change to response, but I'll need to double check if I didn't change anything else.

So to me, the unit tests are verifying the wrong behavior, I'll try and find some time to update them.

But I guess the suggestion using the vendor extension should fix it

**Comment by mzellho** [comment]
Thank you @lordvlad, I'll provide a PR around noon.

**Comment by mzellho** [comment]
--> #426

**Comment by hbelmiro** [comment]
Oh... I think I missed that when I reviewed https://github.com/quarkiverse/quarkus-openapi-generator/pull/386.

I don't see any problem with changing to return `Response` for void methods even when `return-response = false`.

@ricardozanini WDYT?
