### ISSUE TITLE
Gradle Support Example

### ISSUE THREAD

**Issue by messi-gao** [quarkiverse/quarkus-openapi-generator#429]
Could you provide example of gradle support？Thanks！

**Comment by messi-gao** [comment]
@hbelmiro

**Comment by hbelmiro** [comment]
@messi-gao we still don't have an example.
I'm not familiar with Gradle. For Maven, we use the `quarkus:generate-code` task from the [quarkus-maven-plugin](https://quarkus.io/guides/quarkus-maven-plugin). You would have to run the equivalent task for Gradle.
What have you tried?

**Comment by lordvlad** [comment]
its simple:

```
dependencies {
    ....
    implementation("io.quarkiverse.openapi.generator:quarkus-openapi-generator:2.2.8")

}
```

**Comment by hbelmiro** [comment]
Thank you @lordvlad.
Would you like to contribute to the docs with this information? Otherwise, I can do it. Just let me know.
