### ISSUE TITLE
Generated client not usable because of @PartFilename’s value - filename value is missing a supported extension

### ISSUE THREAD

**Issue by patr1kt0th** [quarkiverse/quarkus-openapi-generator#435]
Hi guys. I'm not sure if it really is an issue, but as I have no (good) idea how to solve it, I'll give it a shot.

We're accessing an external (PDF) conversion service and are using `quarkus-openapi-generator` to generate the REST client based on their OpenAPI YAML. We're using `resteasy-reactive` and the generated code for adding data (files) to a conversion job looks like this:

```
    @POST
    @Path("/{jobId}/data/")
    @Consumes({"multipart/form-data"})
    @Produces({"application/json", "application/xml", "application/problem+json", "application/problem+xml"})
    @GeneratedMethod ("addData")
    public DataInfo addData(
        @jakarta.ws.rs.BeanParam AddDataMultipartForm multipartForm,@GeneratedParam("jobId") @PathParam("jobId") String jobId,@GeneratedParam("url") @QueryParam("url") String url
    );

    public static class AddDataMultipartForm {
        @FormParam("options")
        @org.jboss.resteasy.reactive.PartType(MediaType.APPLICATION_JSON)
        public List<Option> options;
        @FormParam("data")
        @org.jboss.resteasy.reactive.PartFilename("dataFile")
        @org.jboss.resteasy.reactive.PartType(MediaType.APPLICATION_OCTET_STREAM)
        public File data;
    }
```

The problematic part for us is `@org.jboss.resteasy.reactive.PartFilename("dataFile")`. The conversion service rejects our requests, as it only supports a bunch of allowed extensions (txt, html, docx, ...), and unfortunately `dataFile` = a filename without an extension, is not one of them.

We've "solved" the issue by simply removing the `@PartFilename` using `maven-replacer-plugin`. The problem with this "solution" was, that it did not work all the time together with `quarkus dev` = sometimes the replacer was triggered correctly, but most of the time it wasn't. After updating both Quarkus (3.2.3.Final) and `quarkus-openapi-generator` (2.2.8) this does not seem to be the case anymore (at least after doing a few test runs), which is great, but I'd still be interested if there's a more elegant solution out there.

Would it make sense to have the `@PartFilename` optional in `multipartFormdataPojo.qute`, e.g. based on some configuration property? Or is there some other way? Thanks a lot for any suggestions.

**Comment by hbelmiro** [comment]
Currently, there's no elegant way of doing that, since [it's hardcoded](        @org.jboss.resteasy.annotations.providers.multipart.PartFilename("{p.baseName}File")) in the template.
I think it makes sense to add two config properties for that. One for making @PartFilename optional, as you suggested, and another one for setting the filename.
Would you like to send a PR?

**Comment by patr1kt0th** [comment]
Thanks for the reply @hbelmiro. Yes, sure, let me check the code in more detail and hopefully, I can come back with a PR by the end of the week.
