### ISSUE TITLE
Spec with schema having additionalProperties: true generates model extending HashMap

### ISSUE THREAD

**Issue by ayhanap** [quarkiverse/quarkus-openapi-generator#442]
A spec file with the following schema

```
      "Priority": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "The description of the issue priority."
          },
          "iconUrl": {
            "type": "string",
            "description": "The URL of the icon for the issue priority."
          },
          "id": {
            "type": "string",
            "description": "The ID of the issue priority."
          },
          "isDefault": {
            "type": "boolean",
            "description": "Whether this priority is the default."
          },
          "name": {
            "type": "string",
            "description": "The name of the issue priority."
          },
          "self": {
            "type": "string",
            "description": "The URL of the issue priority."
          },
          "statusColor": {
            "type": "string",
            "description": "The color used to indicate the issue priority."
          }
        },
        "additionalProperties": true,
        "description": "An issue priority."
      },
```
generates following class
```
public class Priority extends HashMap<String, Object> {

    private String description;

    private String iconUrl;

    private String id;

    private Boolean isDefault;

    private String name;

    private String self;

    private String statusColor;
........
```

So then Jackson maps all fields to this super HashMap although there are separate fields for them. 
There are similar issues on Openapi Tools specific generators for ex spring server which is fixed: https://github.com/OpenAPITools/openapi-generator/issues/1466 

Also default java generator also doesn't generate a model extending HashMap instead has a property HashMap keeping the additional properties.

I think quarkus generator should also generate a model with a similar structure.

**Comment by mcruzdev** [comment]
Hi @hbelmiro, reading the nice proposal from @ayhanap, and thank you for the initial help... 

I think that to implement it we need to add this feature to our `model.qute` template file.

When I add the property `QuarkusJavaClientCodegen#supportsAdditionalPropertiesWithComposedSchema` to `true` the extends of `HashMap` does not exist and the attribute (HashMap<?,?> additionalProperties) does too.


Maybe is necessary to add a new property to maintain compatibility ( I do not know), what do you think?

**Comment by hbelmiro** [comment]
Yes, we need to keep backward compatibility.

**Comment by mcruzdev** [comment]
Hi @hbelmiro, @ricardozanini I think that I can contribute to solving this issue if you want.

**Comment by hbelmiro** [comment]
Sure @mcruzdev. Go ahead please.

**Comment by mcruzdev** [comment]
Hi @ayhanap, how are you? Sorry for delay!

I think that this pull request #504 can solve the issue, could you check it?

**Comment by ayhanap** [comment]
Thanks for the effort @mcruzdev, this is working as intended. 

(I am still using quarkus2, because I am locked on it with another issue.) PR is marked with a backport label, guessing it will be ported. For my use case there is no urgency, I just have a workaround for this.

**Comment by Mettbrot** [comment]
Hey @ayhanap 

> Also default java generator also doesn't generate a model extending HashMap instead has a property HashMap keeping the additional properties.

I am still getting the buggy extends HashMap implementation. How did you generate the properties/additionalProperties mix using the Java generator?

**Comment by ayhanap** [comment]
@Mettbrot You need to set 
quarkus.openapi-generator.codegen.spec.YOUR_SPEC_FILE.additional-properties-as-attribute=true
