### ISSUE TITLE
SUFFIX and PREFIX on generated classes

### ISSUE THREAD

**Issue by marque88** [quarkiverse/quarkus-openapi-generator#471]
Add feature to configure:
- apiNameSuffix
```
quarkus.openapi-generator.codegen.spec.perstore_json.api-name-suffix=CustomApiSuffix
```
- modelNameSuffix
```
quarkus.openapi-generator.codegen.spec.perstore_json.model-name-suffix=CustomModelSuffix
```
- modelNamePrefix 
```
quarkus.openapi-generator.codegen.spec.perstore_json.mode-name-prefix=CustomModelPrefix
```

_Originally posted by @marque88 in https://github.com/quarkiverse/quarkus-openapi-generator/discussions/465_

**Comment by ricardozanini** [comment]
As mentioned in the PR, can you please expand this use case a little bit more? Thank you!
