### ISSUE TITLE
Special characters handling error in version 1.3.10

### ISSUE THREAD

**Issue by bkalas** [quarkiverse/quarkus-openapi-generator#495]
In swagger we have object like this
```
 PatchItemV3:
      type: object
      required:
        - op
        - path
      properties:
        op:
          $ref: '#/components/schemas/PatchOp'
        path:
          type: string
          enum:
            - /status/addressStatus
        value:
          type: object
```
 
and old generated enum looked like this
```
@JsonIgnoreProperties(ignoreUnknown = true)
public class PatchItemV3  {

    private PatchOp op;

    public enum PathEnum {
        _STATUS_ADDRESSSTATUS("/status/addressStatus");
```
in version 1.3.10 generated class is not even compilable and looks like this
````
@JsonIgnoreProperties(ignoreUnknown = true)
public class PatchItemV3  {

    private PatchOp op;

    public enum PathEnum {
        SLASH_STATUS/ADDRESSSTATUS(String.valueOf("/status/addressStatus"));
````

i think it is caused by this commit

https://github.com/quarkiverse/quarkus-openapi-generator/commit/528a04cf4ca25a301a14a3b22c3c99b45311a4f3

**Comment by mcruzdev** [comment]
Hi @ricardozanini, I think that I can help with this bug if @fjtirado does not mind. 

@bkalas, What is the expected result? For each special character should I replace with the name? Or just compile well is ok?

input: `/status/addressStatus`
output: `SLASH_STATUS_Slash_ADDRESSSTATUS`

input: `$`
output: `DOLLAR_symbol`

input: `/users`
output: `SLASH_users`

**Comment by hbelmiro** [comment]
You can definitely send a PR @mcruzdev. Just add @fjtirado as a reviewer, please.

**Comment by bkalas** [comment]
> Hi @ricardozanini, I think that I can help with this bug if @fjtirado does not mind.
> 
> @bkalas, What is the expected result? For each special character should I replace with the name? Or just compile well is ok?
> 
> input: `/status/addressStatus` output: `SLASH_STATUS_SLASH_ADDRESSSTATUS`
> 
> input: `$` output: `DOLLAR_SYMBOL`
> 
> input: `/users` output: `SLASH_USERS`

Hi i think, your suggested solution looks good, should work ok

**Comment by mcruzdev** [comment]
Hi @fjtirado, how are you? Can you review the pull request #510 ? TY!
