### ISSUE TITLE
Configure GH Actions CI to run tests and build on Windows machines

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#5]
See https://github.com/quarkiverse/quarkus-openapi-generator/pull/3#discussion_r804605905

**Comment by RishiKumarRay** [comment]
getting these errors while configuring
![Screenshot from 2022-02-12 09-39-13](https://user-images.githubusercontent.com/87641376/153696022-84bf7e68-fd58-4819-821a-4cc5fe331e2f.png)
 ci

**Comment by ricardozanini** [comment]
@RishiKumarRay, many thanks! We can wait for #3 to be merged. It will fix these formatting problems.

**Comment by ricardozanini** [comment]
@RishiKumarRay can you try again, please?

**Comment by RishiKumarRay** [comment]
@ricardozanini Sure I will do it now

**Comment by RishiKumarRay** [comment]
still getting the errors(i had fetched the changes)
![Screenshot from 2022-02-16 18-46-52](https://user-images.githubusercontent.com/87641376/154272554-8ce1c03f-4cf9-46ef-a1b9-23a264b8de90.png)
@ricardozanini

**Comment by ricardozanini** [comment]
That's really weird since the CI has passed in the main branch. Let me try to fix it locally.

**Comment by ricardozanini** [comment]
Just ran on locally (MacOS) with `mvn -B formatter:validate verify --file pom.xml` and I'm not seeing this same error. @gastaldi maybe this is related to the platform? I'll take a closer look at the `formatter` execution.

**Comment by gastaldi** [comment]
Maybe it's related to how line endings and line breaks are handled in the formatter? Can you run that in a Windows machine?

**Comment by ricardozanini** [comment]
I don't have access to a Windows machine. But, yeah might be that:

```xml
          <configuration>
            <configFile>eclipse-format.xml</configFile>
            <lineEnding>LF</lineEnding>
            <skip>${format.skip}</skip>
          </configuration>
```

@RishiKumarRay, can you try adding to the workflow file a `-Dformat.skip=true`?

**Comment by RishiKumarRay** [comment]
@ricardozanini In which file do i have to add? build.yml

**Comment by RishiKumarRay** [comment]
i have added let me test @ricardozanini

**Comment by ricardozanini** [comment]
@RishiKumarRay I imagine you can create another file or profile (not sure if this is valid) to run on a Windows since the command should not be changed on Linux.

**Comment by RishiKumarRay** [comment]
@ricardozanini sure i will do this , give me some time

**Comment by ricardozanini** [comment]
@gastaldi maybe we can create a profile for Windows in the quarkiverse BOM? 🤔

**Comment by RishiKumarRay** [comment]
@ricardozanini i did testing on windows after adding that and that is still failing on windows
![Screenshot from 2022-02-16 19-45-48](https://user-images.githubusercontent.com/87641376/154283020-64d4d6c7-ac7b-42f3-86b7-1491b9fc7589.png)

**Comment by ricardozanini** [comment]
I think you must escape the command. Try this:

```powershell
mvn -B formatter:validate verify -Dformat\.skip=true --file pom.xml
```

**Comment by RishiKumarRay** [comment]
yeah sure let me try this

**Comment by RishiKumarRay** [comment]
@ricardozanini that too is not working

**Comment by RishiKumarRay** [comment]
'-Dformat\.skip=true' i read somewhere we have to quote this, Let me try this

**Comment by ricardozanini** [comment]
If you need to quote it, you should do:

```powershell
mvn -B formatter:validate verify -D"format.skip"=true --file pom.xml
```

Not sure if this will do, thou. I don't have a Windows machine to test it. :(

**Comment by RishiKumarRay** [comment]
Yeah me too , look at this https://stackoverflow.com/questions/6347985/cannot-run-maven-using-mvn-d-argument-within-microsoft-powershell-but-works 
maybe you can find something since you are aware of java
@ricardozanini

**Comment by RishiKumarRay** [comment]
> If you need to quote it, you should do:
> 
> ```powershell
> mvn -B formatter:validate verify -D"format.skip"=true --file pom.xml
> ```
> 
> Not sure if this will do, thou. I don't have a Windows machine to test it. :(

Although it took time but in the end this one failed too but with different you may want to see this
![Screenshot from 2022-02-16 20-07-29](https://user-images.githubusercontent.com/87641376/154287296-c60f6545-09db-49f0-a0f3-c9b6c7b12823.png)

**Comment by RishiKumarRay** [comment]
@ricardozanini 
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project quarkus-openapi-generator-deployment: There are test failures.
Error:  
Error:  Please refer to D:\a\quarkus-openapi-generator\quarkus-openapi-generator\deployment\target\surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :quarkus-openapi-generator-deployment

**Comment by ricardozanini** [comment]
I need to know the error in order to fix it. Can you provide the log files included here?

```D:\a\quarkus-openapi-generator\quarkus-openapi-generator\deployment\target\surefire-reports for the individual test results.```

**Comment by RishiKumarRay** [comment]
@ricardozanini i didn't get it but you can visit this link , and everything is present here 
https://github.com/RishiKumarRay/quarkus-openapi-generator/runs/5217782988?check_suite_focus=true
let me know if you are asking for anything else

**Comment by gastaldi** [comment]
I built in a Windows VM and saw this: 

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/ggastald/quarkus-openapi-generator/deployment/target/test-classes/openapi/petstore-openapi.json
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContentFromLocation(OpenAPIV3Parser.java:225)
        ... 75 more
```

**Comment by ricardozanini** [comment]
@gastaldi, many thanks! It might be a problem with the Swagger parser. I'll take a closer look into it! Many thanks, guys!

@RishiKumarRay, please open the PR. I don't think the problem is related to the GHA configuration. We can keep the formatting verification and merge it after fixing the Windows errors. Thank you!

**Comment by ricardozanini** [comment]
@RishiKumarRay can you add this configuration to the build?

> Another information: Setting core.autocrlf=false in the ~/.gitconfig in Windows seems to fix the formatter problem (at least I didn't see the error with that setting on)

@gastaldi nailed it!

**Comment by ricardozanini** [comment]
> @ricardozanini should i create a new file for windows only ? I mean instead of running linux and windows together should i separate the files as the commands would be different

I think that now that we have this property set, should work for both. So you can keep the same configuration.

**Comment by gastaldi** [comment]
> @ricardozanini is it like this steps: - name: Prepare git run: git config --global core.autocrlf false

Sounds good. Don't forget that this needs to be run before `actions/checkout` 👍🏻

**Comment by RishiKumarRay** [comment]
yeah let me try this

**Comment by RishiKumarRay** [comment]
@ricardozanini i tried previously with that command but it failed later on i used this command mvn -B formatter:validate verify -D"format.skip"=true --file pom.xml but this one failed too
![Screenshot from 2022-02-16 20-55-15](https://user-images.githubusercontent.com/87641376/154297162-a79b8c4e-4482-476c-8f7b-0e9c458b0885.png)

**Comment by ricardozanini** [comment]
@RishiKumarRay it will fail because we have a bug. The error we can't see is the formatted one with the configuration provided by @gastaldi

**Comment by RishiKumarRay** [comment]
@ricardozanini i also added the gitconfig what to do now?

**Comment by ricardozanini** [comment]
> @ricardozanini i also added the gitconfig what to do now?

If you have added the configuration, we are good. Just open the PR that I fix after #7

**Comment by RishiKumarRay** [comment]
@ricardozanini raised the PR

**Comment by ricardozanini** [comment]
@RishiKumarRay no need to have the `format.skip` option now that we have the `core.autocrlf` configuration in place.
