### ISSUE TITLE
Readme: the Quarkus Apicurio Extension is no more.

### ISSUE THREAD

**Issue by rkraneis** [quarkiverse/quarkus-openapi-generator#502]
The paragraph talking about the Quarkus Apicurio Extension should be removed.

Edit: after further investigation, it may still work with the generic maven plugin ([OpenApi2Quarkus.java](https://github.com/Apicurio/apicurio-codegen/blob/main/core/src/main/java/io/apicurio/hub/api/codegen/OpenApi2Quarkus.java))

**Comment by hbelmiro** [comment]
@ricardozanini any thoughts?

**Comment by ricardozanini** [comment]
@carlesarnal do we have an alternative?

**Comment by carlesarnal** [comment]
This is why I have created https://github.com/quarkiverse/quarkus-openapi-generator/pull/482.

**Comment by akram** [comment]
Hi folks,

is it interesting to mention a workaround? 
is the use of the apicurio maven plugin a valid workaround for that?

I am doing this:

```
  <build>
    <plugins>
      <plugin>
        <groupId>io.apicurio</groupId>
        <artifactId>apicurio-codegen-maven-plugin</artifactId>
        <version>1.1.1.Final</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <projectSettings>
                <javaPackage>com.example.api</javaPackage>
              </projectSettings>
              <inputSpec>src/main/resources/openapi.json</inputSpec>
            </configuration>
          </execution>
        </executions>
      </plugin>
  </plugins>
</build>
```

**Comment by ricardozanini** [comment]
@carlesarnal is this solved by your PR?

**Comment by carlesarnal** [comment]
Yes, the extension that existed in apicurio is now the one added to this project. In response to @akram yes, the maven plugin is a different wrapper around the same tool, so it's perfectly fine to use it (although I really recommend you using the quarkus extension if you're using Quarkus.)
