### ISSUE TITLE
add quarkus code starter

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-openapi-generator#542]
Just tried this extension against ynab api and its awesome!

What would be really awesome though if the extension had a codestarter so when you do:

`quarkus create app -x quarkus-openapi-generator,picocli ynac`

it would create project that has i.e. `src/main/openapi/petstore.json` + one or two properties in the `application.properties` to have it all setup. 

yes its minimal steps you need but with this I would just have to update the petstore.json file.

**Comment by mcruzdev** [comment]
Hi @hbelmiro, can you assign it to me? I will take a look at this.
