### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#599]
It seems like a documentation preview file is conflicting with existing ones.

https://github.com/quarkiverse/quarkus-openapi-generator/actions/runs/7269277326/job/19828229759?pr=597

**Comment by hbelmiro** [comment]
@ricardozanini @luanbrdev @mcruzdev this issue is preventing us from merging new PRs. I think I won't have time to fix it this week. So, if any of you guys could take a look, it would be awesome.

**Comment by mcruzdev** [comment]
Hi @hbelmiro,

I think that the artifact name cannot be duplicated with the `actions/upload-artifact@v4` version. We have a matrix strategy for building workflow ( with Java 11, Java 17, Ubuntu, and Windows) and the name of the artifact (site) is the same for the running workflow.

We need to add a different name for each one but to download (`dawidd6/action-download-artifact@v3` on `preview.yml` workflow), we need only one. I opened a pull request, to see if makes sense.
