### ISSUE TITLE
Don't deploy doc previews in PRs that don't change docs

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#603]
To avoid [these errors](https://github.com/quarkiverse/quarkus-openapi-generator/pull/600#issuecomment-1867897181), we should try to deploy doc previews only in PRs that change documentation.

**Comment by ricardozanini** [comment]
@hbelmiro I think it's valid to keep the preview running. The problem was related to our token, I couldn't find another reason. If you have it, please let me know! Cheers!

**Comment by hbelmiro** [comment]
Cool. So, I think we can close it.
