### ISSUE TITLE
Extend Support for code generation of Async Api

### ISSUE THREAD

**Issue by sneeve** [quarkiverse/quarkus-openapi-generator#617]
Hi,
Is there a way to use the quarkus-openapi-generator for code generation of async api. Is there a plan to provide support for code generation of async api?

Thanks,

**Comment by hbelmiro** [comment]
Hi @sneeve. There's a different extension for AsyncAPI.
https://github.com/quarkiverse/quarkus-asyncapi

**Comment by sneeve** [comment]
Given a yaml/json file the quarkus-asyncapi generate the code for the specific channels, publishers, consumers etc. From the readme it looks like it scans the code and provides a yaml

**Comment by hbelmiro** [comment]
@fjtirado can you answer @sneeve's question, please?

**Comment by sneeve** [comment]
@fjtirado - Will the quarkus-asyncapi plugin, when given a yaml/json file generate the code for the specific channels, publishers, consumers etc specified in the yaml. From the readme it looks like it scans the code and provides a yaml
