### ISSUE TITLE
Implement reactive support for server side code generation

### ISSUE THREAD

**Issue by carlesarnal** [quarkiverse/quarkus-openapi-generator#663]
https://github.com/quarkiverse/quarkus-openapi-generator/pull/482 adds support for generating server stubs from OpenAPI definitions. This only supports for now classic. The underlying library, Apicurio Codegen, also supports reactive generation. Use the capabilities of the library to implement reactive support in the extension.

**Comment by lprocx** [comment]
Is there any indication of when this could be available? I'm currently generating code, but changing it manually every time to make it reactive. Would be great if it's going to work automatically :-)
