### ISSUE TITLE
Specified path in yaml gets URL encoded

### ISSUE THREAD

**Issue by ennishol** [quarkiverse/quarkus-openapi-generator#664]
Hello,
when an API specification defines path like this:
```
/?unused:
```
the generated client does not preserve the specified URL and encodes it to the path to `/%3Funused`
The request log:
```
[org.apa.htt.imp.exe.MainClientExec] (executor-thread-1) Executing request POST /%3Funused HTTP/1.1
[org.apa.htt.headers] (executor-thread-1) http-outgoing-0 >> POST /%3Funused HTTP/1.1
[org.apa.htt.wire] (executor-thread-1) http-outgoing-0 >> "POST /%3Funused HTTP/1.1[\r][\n]"
```

Please change it to use the original spec without modifying or add some option to disable it for given API file or a path

To reproduce use tests in the attached demo

[demo.tar.gz](https://github.com/quarkiverse/quarkus-openapi-generator/files/14344061/demo.tar.gz)

Thank you very much!

**Comment by mcruzdev** [comment]
Hi @ennishol thank you for this issue!

If you want, open a pull request to solve this issue, what do you think?

**Comment by ricardozanini** [comment]
@ennishol, this is not an issue in this project. The path segment per [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3), can't have the `?` character, hence the engine is encoding it. So it's working as it's meant to be. See here a more detailed response: https://stackoverflow.com/a/4669755/1354502

In your case, the URI interpreter will see the first `?` in the path and it will break it considering `unused` to be a querystring parameter with an empty var. So it will break your API anyway if we not encode the `?` char.

My suggestion: remove this path from your OpenAPI file or change it to `unused`. It smells a workaround anyway.

**Comment by ennishol** [comment]
@ricardozanini Yes. that is what I'm doing. But I wrongly assumed it would be a problem with the open-api generator and wanted to report a bug/improvement. Sorry for bothering you

**Comment by ricardozanini** [comment]
No worries! We are happy to have you here and using our project 👍
