### ISSUE TITLE
Move `docs` back to root

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-openapi-generator#669]
Removing `docs` from the root has broken the Quarkiverse docs workflow. See https://github.com/quarkiverse/quarkiverse-docs/actions/runs/8030061612/job/21937044854?pr=143

As a rule of thumb, regardless on how many extensions the repository has, there should be only one docs directory in the root

**Comment by ricardozanini** [comment]
@mcruzdev can you take a look if you have room?

**Comment by mcruzdev** [comment]
Yeah surely! I will get this one today, TY for ping me.

**Comment by ricardozanini** [comment]
Thak you for taking care of it!
