### ISSUE TITLE
server extension: HTTP status 201 instead of 200 for POST?

### ISSUE THREAD

**Issue by markuszoeller** [quarkiverse/quarkus-openapi-generator#670]
I'm using a locally built jar for the server generation: https://github.com/quarkiverse/quarkus-openapi-generator/pull/482#issuecomment-1964132436 and use the example of `POST  /pet` defined in https://github.com/quarkiverse/quarkus-openapi-generator/blob/a8e255cb480b3cb3ea24e1079725a48ff81d3958/server/deployment/src/test/resources/openapi/petstore-openapi.json#L112-L155

I'd rather have a HTTP status code of "201 Created" instead of "200 OK" for when the resource got created but it seems I cannot influence that. The generated code looks like this:
```java
// [...]

@Path("/pet")
public interface PetResource {

  // [...]

  /**
   * <p>
   * Add a new pet to the store
   * </p>
   * 
   */
  @POST
  @Produces({"application/xml", "application/json"})
  @Consumes({"application/xml", "application/json", "application/x-www-form-urlencoded"})
  Pet addPet(@NotNull Pet data);

// [...]
``` 

Even when I change it in the spec to `"201"` like this:
```json
      "post": {
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "description": "Add a new pet to the store",
        "operationId": "addPet",
        "requestBody": {
          "description": "Create a new pet in the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
```
the swagger UI still says it returns a 200 (same if I try it with `curl`):
<img width="1768" alt="image" src="https://github.com/quarkiverse/quarkus-openapi-generator/assets/7761429/6613af0d-af91-412d-bfd5-be10edc7ba1c">

In the quarkus docs (https://quarkus.io/guides/resteasy-reactive), the `ResponseBuilder` is shown to set all kinds of details, including HTTP status code and for a POST, the location: https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive-common/2.16.0.CR1/org/jboss/resteasy/reactive/RestResponse.html#created(java.net.URI)

How can I change the HTTP response for the generated code?

**Comment by carlesarnal** [comment]
Hello @markuszoeller, I'm not sure what's your expectation here. If it's for the extension to add the @ApiResponse annotation then that is simply not possible since that annotation is coming from swagger, not from JAX-RS, thus why we're not adding it.

**Comment by markuszoeller** [comment]
> Hello @markuszoeller, I'm not sure what's your expectation here.

Hi @carlesarnal I'd like to have a different HTTP status code for responses to a POST request. Right now the status code in a response to a POST request will be 200, but I'd like to have 201.

Maybe, instead of the currently generated code which returns the bean, here `Pet`:
```
@Path("/pet")
public interface PetResource {

  // [...]

  /**
   * <p>
   * Add a new pet to the store
   * </p>
   * 
   */
  @POST
  @Produces({"application/xml", "application/json"})
  @Consumes({"application/xml", "application/json", "application/x-www-form-urlencoded"})
  Pet addPet(@NotNull Pet data);
```
it could be 
```
  RestResponse<Pet> addPet(@NotNull Pet data);
```
Does that make any sense? I'm still new to the framework.

**Comment by carlesarnal** [comment]
> > Hello @markuszoeller, I'm not sure what's your expectation here.
> 
> Hi @carlesarnal I'd like to have a different HTTP status code for responses to a POST request. Right now the status code in a response to a POST request will be 200, but I'd like to have 201.
> 
> Maybe, instead of the currently generated code which returns the bean, here `Pet`:
> 
> ```
> @Path("/pet")
> public interface PetResource {
> 
>   // [...]
> 
>   /**
>    * <p>
>    * Add a new pet to the store
>    * </p>
>    * 
>    */
>   @POST
>   @Produces({"application/xml", "application/json"})
>   @Consumes({"application/xml", "application/json", "application/x-www-form-urlencoded"})
>   Pet addPet(@NotNull Pet data);
> ```
> 
> it could be
> 
> ```
>   RestResponse<Pet> addPet(@NotNull Pet data);
> ```
> 
> Does that make any sense? I'm still new to the framework.

The generated code is just a stub, so it doesn't return a 200 or a 201, that's up to your implementation. The only way to do that at the interface level is what I shared, using swagger specific annotations, and that is a no-go since it would imply adding another external dependency to the generator. If you're aware of any other way, I would be more than happy to explore it.

**Comment by crazybolillo** [comment]
I think this still relevant. When creating new objects usually 201 is returned instead of 200. However Quarkus defaults to HTTP 200 when a method returns an object. This breaks downstream integrations, for example a python client auto generated from the same `openapi.yaml` will not parse the body of a HTTP 200 response as it expects it to be 201.

I tried using `@ResponseStatus(201)` on the overridden method (implementation) but it did not work. In case this helps anyone, the work around I used was setting `x-codegen-returnType` to `jakarta.ws.rs.core.Response` so the interface method returns a `Response` and I can customize the HTTP code.

I think ideally the interface should already come in with `ResponseStatus` or something similar.

**Comment by mcruzdev** [comment]
@markuszoeller @crazybolillo did you see this documentation: https://docs.quarkiverse.io/quarkus-openapi-generator/dev/server.html#_x_codegen_returntype, it is a new documentation, and probably can help you to achieve what you need.

**Comment by gerdint** [comment]
I am having issues with this too, wanting to use status 202 for the happy path in accordance with a spec I have received from a supplier.

@crazybolillo Using `org.jboss.resteasy.reactive.RestResponse<T>` (as in the example above) would enable strongly typed interfaces while still providing the flexibility for modelling various status codes in return values (among other things).

@mcruzdev But is the case that the x-codegen extensions are only available to put inside the actual spec? In our case we don't control the spec but just want to generate an API from it for testing purposes. I guess we could postprocess the spec and insert x-codegen in it but it would be nice if this was configurable via extension properties or the like.

**Comment by gerdint** [comment]
Right now my workaround is throw a jakarta.ws.rs.WebApplicationException in the interface implementation method body with the entity like this:
```
        throw new WebApplicationException(
                Response.accepted(myEntity).build()
        );
```
... which is not so nice and I loose the static type-safety again since WebApplicationException does not accept `org.jboss.resteasy.reactive.RestResponse<T>` (though I could probably find some other more appropriate exception or write my own exception mapper or sth). And especially it's not so nice to return the nominal return value using an exception...

**Comment by mcruzdev** [comment]
Hi @gerdint, probably you are using apicurio generator. I am working on this, in your case probably the best approach is to use configuration.

**Comment by mcruzdev** [comment]
@gerdint Here we go https://github.com/quarkiverse/quarkus-openapi-generator/pull/1608

**Comment by gerdint** [comment]
> Hi [@gerdint](https://github.com/gerdint), probably you are using apicurio generator. I am working on this, in your case probably the best approach is to use configuration.

Yes. Mostly because it looked like the best supported one. I would be open to try the other one though if it would support my use case better. Not sure what you mean by "configuration"? But #1608 looks suitable indeed!
