### ISSUE TITLE
Rearrange docs index page to clarify the extensions structure

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#672]
Currently, we have docs only for the client extension. We should rewrite the [index.adoc](https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/docs/modules/ROOT/pages/index.adoc) page to clarify that this is a multipurpose extension for OpenAPI and add parent sections for Client, Server, and Wiremock in the future.

**Comment by ricardozanini** [comment]
@carlesarnal can you handle this once you migrate your docs?

**Comment by mcruzdev** [comment]
Hi @ricardozanini I can handle this one today!

**Comment by mcruzdev** [comment]
Sorry for delay, I was very busy, tomorrow I will try to send a pull request!

**Comment by ricardozanini** [comment]
No rush!
