### ISSUE TITLE
Update the issues template to help users identify which extension they are using

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#677]
Since we now support a `server` extension, it would be beneficial to the project to have an issue template with the following fields:

**Extension** (checkbox style input): `server` or `client` (here we should be able to add a correct label to the issue)
**Java version**: output of java --version
**Quarkus version**: Platform Quarkus version used in the project

And as usual, **Description** and **Reproducer** in case of bugs.

**Comment by mcruzdev** [comment]
+1

**Comment by mcruzdev** [comment]
Hi @gmalheiro, if you comment here I can assign it for you!

**Comment by gmalheiro** [comment]
Hey @mcruzdev! ! Commented!

**Comment by mcruzdev** [comment]
Assigned, thank you @gmalheiro!

If you have any questions you can call me.

**Comment by gmalheiro** [comment]
Hey @mcruzdev!

Here is the PR: https://github.com/quarkiverse/quarkus-openapi-generator/pull/726

I would appreciate a code review to ensure the issues template meets expectations. Additionally, I would like feedback on the forking and PR submission process to confirm if I've done everything correctly.

Thanks for everything!
