### ISSUE TITLE
Generate validation in required attibute

### ISSUE THREAD

**Issue by EPC-SOG** [quarkiverse/quarkus-openapi-generator#690]
It is possible to add validation contrains in required attributs when generated client api ?

**Comment by EPC-SOG** [comment]
Example:

@GET
    @Path("/identifier")
    @Produces({"application/json"})
    Identifiers getAgreementIdentifier(@GeneratedParam("test") @QueryParam("test") **@NotNull** String test) throws RestClientException;

Because in swagger, test query parameter is requied

**Comment by ricardozanini** [comment]
@EPC-SOG you can apply the changes in this template by reading the OpenAPI model and identifying that the field is required:

https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/client/deployment/src/main/resources/templates/libraries/microprofile/api.qute

Also, I'd like to see min/max, number, and custom validations if provided. Not only required. WDYT?

**Comment by EPC-SOG** [comment]
Hi,

Example of swaager : `{
  "swagger": "2.0",
  "info": {
    "title": "test",
    "description": "Description test",
    "version": "1.0.0",
    "contact": {}
  },
  "tags": [
    {
      "name": "test",
      "description": "Gestion of test"
    }
  ],
  "paths": {
    "/api/v1/test": {
      "get": {
        "tags": [
          "test"
        ],
        "summary": "test of test",
        "description": "return test object",
        "operationId": "getTestObject",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "testName",
            "in": "query",
            "description": "Numéro de mobile affilié au contrat",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Test template"
          }
        }
      }
    }
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  },
  "definitions": {
  }
}`

pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
        xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

 

    <artifactId>test</artifactId>
    <version>1.0.0</version>

    <properties>
        <compiler-plugin.version>3.11.0</compiler-plugin.version>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.8.3</quarkus.platform.version>
        <surefire-plugin.version>3.1.2</surefire-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.2.19</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.openapi.generator</groupId>
            <artifactId>quarkus-openapi-generator</artifactId>
            <version>2.4.1</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-config-yaml</artifactId>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>application.yaml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
`

At generation, i have not @NonNull for testName query param

**Comment by EPC-SOG** [comment]
I find the problem, thks

**Comment by EPC-SOG** [comment]
in https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/client/deployment/src/main/resources/templates/libraries/microprofile/queryParams.qute

replace beanValidationCore.qute to include beanValidation.qute no ?

**Comment by ricardozanini** [comment]
You can add the `@NonNull` annotation here: https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/client/deployment/src/main/resources/templates/libraries/microprofile/beanValidationCore.qute

**Comment by ricardozanini** [comment]
Also, you have to figure out where in the model we set this property: `{#if param.useBeanValidation}`. I don't remember. Just make sure that either your swagger has this info or the extension property.

**Comment by EPC-SOG** [comment]
Sorry, I test the last version and impossible to have @NotNull in parameter.queryparam.required true add in generation in test integration code

**Comment by ricardozanini** [comment]
Yes, because as I pointed out in my last comment, you must add it to the template in a new PR. 👍

**Comment by ricardozanini** [comment]
@gianluca-colaianni-axa yes, it is. Currently only `NotNull` is not supported, which you can send a PR to fix it if you can.
