### ISSUE TITLE
Yaml file not accepted as openapi descriptor for the server generator

### ISSUE THREAD

**Issue by jtama** [quarkiverse/quarkus-openapi-generator#693]
The documentation specifies that the following format are accepted : 

> We support JSON, YAML and YML extensions.

The extension actually only sypports json files.

I guess this is because : 

1. The `ApicurioOpenApiServerCodegen` class override the deprecated method `inputExtension`, instead of `inputExtensions` which can return an array of extensions.
2. `io.apicurio.datamodels.Library` doesn't support `yaml` format.

I think it should be corrected in the documentation for the moment, and possibly track the upstream support for `yaml` format to support it asap.

thanks

**Comment by hbelmiro** [comment]
> We support JSON, YAML and YML extensions.

This is valid for the client generator. We need to fix the docs.

**Comment by jtama** [comment]
Sorry for the lack of accuracy, I was speaking about the server generator

**Comment by ricardozanini** [comment]
@carlesarnal can you ptal?
