### ISSUE TITLE
template customization using gradle

### ISSUE THREAD

**Issue by jahn-idt** [quarkiverse/quarkus-openapi-generator#696]
I can't seem to get custom templates for `api.qute` to work version 2.3.0.

https://github.com/quarkiverse/quarkus-openapi-generator/pull/439
seems to use `Path templateDir = context.workDir().resolve("classes").resolve("templates");`
which doesn't work in the gradle build directory layout.

**Comment by ricardozanini** [comment]
@jahn-idt I'm not familiar with gradle. Do you mind sending a PR? cc @hbelmiro @mcruzdev are you guys familiar with Gradle?

**Comment by hbelmiro** [comment]
I barely know the basics.

**Comment by mcruzdev** [comment]
+1 with @hbelmiro
