### ISSUE TITLE
Enable snapshots for our plugins

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#716]
Discussion context:

> You can add this workflow file to enable that: https://github.com/quarkiverse/quarkus-prettytime/blob/main/.github/workflows/snapshot-deploy.yml

> _Originally posted by @gastaldi in https://github.com/quarkiverse/quarkus-openapi-generator/discussions/698#discussioncomment-9355377_

**Comment by mcruzdev** [comment]
Closed by #717

**Comment by mcruzdev** [comment]
Closed by #717
