### ISSUE TITLE
Add support to variables for server definition

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#72]
Host names and service ports often differ from one environment to another. It would be nice if we could use different information based on environment variables.

https://swagger.io/docs/specification/api-host-and-base-path/

```yaml
---
openapi: 3.0.3
info:
  title: translation-service API
  version: 1.0
servers:
  - url: http://{hostname}:{port}/
    variables:
      hostname:
        default: 'localhost'
        description: 'Hostname of the translation-service'
      port:
        default: '8080'
        description: 'Port of the translation-service' 
```

As a workaround we can use Quarkus properties to define the entire URL.
https://quarkus.io/guides/rest-client#create-the-configuration

**Comment by ricardozanini** [comment]
We already support this. The Rest Client is highly configurable. Or am I missing something? Why would I change the spec to add a placeholder like this while we have the Rest Client configuration? 

See: https://github.com/quarkiverse/quarkus-openapi-generator/blob/0.6.1/integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/WiremockOpenWeather.java#L18

You can already change the URL via `quarkus.rest-client.<spec_file_name>.url` property.

**Comment by ricardozanini** [comment]
Oh, you meant **server template**? I need to review the internal generator, if I'm not mistaken these variables are already parsed. Need to understand what we are doing with them internally. 

The base URI attribute in the generated clients uses the first server from the list.
