### ISSUE TITLE
How to skip generating APIs and control target packages

### ISSUE THREAD

**Issue by beatngu13** [quarkiverse/quarkus-openapi-generator#741]
Before we were using the OpenAPI Maven Plugin along with the [`java`](https://openapi-generator.tech/docs/generators/java/) (client) generator. It has a bunch of helpful options such as:

* `generateApis`: whether to generate APIs or not.
* `apiPackage`: which package to use for API classes.

Is there a way to achieve this with the Quarkus OpenAPI generator? Or more generally: what exact generator is being used under the hood and how can we supply corresponding configuration options?

**Comment by mcruzdev** [comment]
Hi @beatngu13, thank for the question!

> Is there a way to achieve this with the Quarkus OpenAPI generator?

I will answer below:

> generateApis: whether to generate APIs or not.

There is no option for enable/disable the API generation.

> apiPackage: which package to use for API classes.

If you want to change the base package in which the classes are generated, use the `quarkus.openapi-generator.codegen.spec.<filename>.base-package` property. 

> [!NOTE]
> The base-package is for specified for all generated classes.

 If I didn't answer your question well, you can tell me and I'll try to improve the answer.

**Comment by beatngu13** [comment]
Too bad those options don't exist. We, therefore, had to fall back to the OpenAPI Maven Plugin. Anyway, thank you! 🙏

**Comment by mcruzdev** [comment]
@beatngu13 It is relatively easy to implement. Can you send a PR, I can help you with questions on [Zulip](https://quarkusio.zulipchat.com/#user/621866).
