### ISSUE TITLE
Client Generator: java.util.Set is not imported but used when type has uniqueItems=true

### ISSUE THREAD

**Issue by ddelbondio** [quarkiverse/quarkus-openapi-generator#779]
Given this type: 

```json
"Type": {
  "type": "object",
  "properties": {
    "tags": {
      "uniqueItems": true,
      "type": "array",
      "items": {
        "type": "string"
      },
    }
  }
}
```

The code correctly generates this as `public Set<String> tags;`, but the file is missing the `java.util.Set` import

**Comment by hbelmiro** [comment]
@mcruzdev do you have the bandwidth to take a look at this?
It's probably code generated by the underlying library. Maybe we need to import collections and other classes from the standard library.

**Comment by mcruzdev** [comment]
> @mcruzdev do you have the bandwidth to take a look at this? It's probably code generated by the underlying library. Maybe we need to import collections and other classes from the standard library.

Of course @hbelmiro, I will take this one tomorrow!

**Comment by mcruzdev** [comment]
@hbelmiro do you know why we are using `import java.lang.reflect.Type;` import statement?

**Comment by hbelmiro** [comment]
> @hbelmiro do you know why we are using `import java.lang.reflect.Type;` import statement?

@mcruzdev I don't.
