### ISSUE TITLE
Source Root not detected by intellij when building with gradle

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-openapi-generator#791]
As stated in the title, the generated source root is not detected by intellij when building with gradle

I am not sure if this problem is coming from this plugin or from quarkus itself. 

The project compile correctly, but intellij does not recognize the generated source root,

Quick fix is to add the following to build.gradle:

```
sourceSets {
    main {
        java {
            srcDirs "$buildDir/classes/java/quarkus-generated-sources/open-api-json"
        }
    }
}
```

**Comment by rmanibus** [comment]
reproducer: https://github.com/rmanibus/quarkus-openapi_117

**Comment by ricardozanini** [comment]
That doesn't happen on Maven.

**Comment by ngoduongkha** [comment]
Hi @rmanibus, I am facing the same issue as you. Would you happen to have any solutions?

**Comment by rmanibus** [comment]
The quick fix mentioned in my message is working (you might have to add other folders, this is only for json)
