### ISSUE TITLE
Generate client stubs other than java

### ISSUE THREAD

**Issue by nimo23** [quarkiverse/quarkus-openapi-generator#814]
Actually, this plugin produces java cliens by openapi definitions declared in the project. Would it be possible to pass also other client code (e.g. typescript, javascript, etc. ).

Use case:
1. I use the openapi annotations by `quarkus-smallrye-openapi`
2. Quarkus will generate openapi-file on every build.
3. this plugin (`quarkus-openapi-generator`) will generate the `typescript`  or `javascript` files according to _openapi annotations defined by the java classes_ or _openapi-file_. The client stubs will be generated  under a given path (by default `src/main/resources/META_INF/openapi-client/`).

Is this actually possible with this plugin? If so, how sould I do the maven configuration for this use case.

**Comment by hbelmiro** [comment]
@nimo23 this is not what this extension is intended for.
For your scenario, you can use https://openapi-generator.tech, which can [generate code for several languages](https://openapi-generator.tech/docs/generators), without involving any Java code.
