### ISSUE TITLE
Quarkus LTS support

### ISSUE THREAD

**Issue by brice-laurencin** [quarkiverse/quarkus-openapi-generator#831]
With quarkus now supporting LTS versions, it feels like the extension should support those LTS versions for their support timeframe.

I clearly don't have any idea how it could move forward.
But I'd be happy to help if I can.

**Comment by hbelmiro** [comment]
We'll probably have multiple branches for each Quarkus version, like when we used to support Quarkus 3 and 2.

@ricardozanini @gastaldi thoughts?

**Comment by gastaldi** [comment]
@hbelmiro exactly. Some projects like https://github.com/quarkiverse/quarkus-artemis already do this

**Comment by ricardozanini** [comment]
@hbelmiro Yes, we have to branch from the main, roll back to LTS, and release a new version from this branch. We can have the same number but with a suffix like `1.2.3-lts`.

@brice-laurencin I can create the branch. Can you work on a patch to follow the LTS in this new branch?

**Comment by brice-laurencin** [comment]
I can try, but I'm not sure I see all that must be done.
As you mentioned, I'd go from `main` and downgrade the quarkus version.

(And I might not be able to do this this week, but next week will be fine)

**Comment by ricardozanini** [comment]
@jota-coelho We are open to contributions. 

I created the `main-lts` branch here: https://github.com/quarkiverse/quarkus-openapi-generator/tree/main-lts

Any PRs should be opened there, and the documentation should be updated to tell users about it. Once it's done, I can do the release.

@brice-laurencin once you open the PR, we can discuss more details if needed.

**Comment by brice-laurencin** [comment]
don't we want a branch per current LTS?
[looks like we have 2 at the moment](https://endoflife.date/quarkus-framework) but I fail to find this info on the [quarkus site](quarkus.io).

**Comment by ricardozanini** [comment]
@brice-laurencin I don't think we have the resources to keep up with the three branches. We can keep up with the latest LTS.

**Comment by brice-laurencin** [comment]
@ricardozanini technically, current `main-lts` references Quarkus 3.15.1, so it's already linking the latest LTS patch.

So I suppose everything is good?
Maybe we need to find a proper version pattern for those versions.

**Comment by ricardozanini** [comment]
We can support the later LTS instead. I think it will be more helpful for the community. 

The version pattern could be `1.2.3-lts`.

**Comment by hbelmiro** [comment]
[We're about to support 3.16](https://github.com/quarkiverse/quarkus-openapi-generator/pull/836#issuecomment-2450129694).

**Comment by ricardozanini** [comment]
@hbelmiro @brice-laurencin the idea is to support an old LTS, in this case Quarkus 3.8 LTS.

**Comment by hbelmiro** [comment]
My point is that we're close to supporting 3.16 in `main`. Once we do that, I'm assuming we would support 3.15 in `main-lts`.
That said, it's probably better just to wait for 3.16 than invest time to support 3.8 just for a few days.

**Comment by ricardozanini** [comment]
@hbelmiro yes, agreed.

**Comment by brice-laurencin** [comment]
Perfect then.
It sounds like this subject is treated with the `2.6.0-lts` version being available.

Does the build process ensure any feature pushed to `main` falls to `mains-lts` as well?

**Comment by hbelmiro** [comment]
@brice-laurencin we have an automation for that. We add the `backport-main-lts` label and a bot cherry-picks the commit to `main-lts`.
Ex.: https://github.com/quarkiverse/quarkus-openapi-generator/pull/849
