### ISSUE TITLE
Expose `serializableModel` property as a Quarkus configuration property

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#869]
Currently, we set the property `serializableModel` defaults to `false`. Ideally, this property should be exposed as `quarkus.openapi.generator.codegen.serializableModel: true|false`.

**Comment by denvitaharen** [comment]
@ricardozanini Should it rather be on every single spec instead? Or do you think that if you have multiple specs generating then you want them all with serializable?

`quarkus.openapi-generator.codegen.spec.petstore_json.serializableModel=true` seams like an better solution in my opinion :)

**Comment by mcruzdev** [comment]
> quarkus.openapi-generator.codegen.spec.petstore_json.serializableModel=true seams like an better solution in my opinion :)

+1

**Comment by ricardozanini** [comment]
> @ricardozanini Should it rather be on every single spec instead? Or do you think that if you have multiple specs generating then you want them all with serializable?
> 
> `quarkus.openapi-generator.codegen.spec.petstore_json.serializableModel=true` seams like an better solution in my opinion :)

Yes, it's for each spec. I didn't write it there because I was lazy.

**Comment by denvitaharen** [comment]
> > @ricardozanini Should it rather be on every single spec instead? Or do you think that if you have multiple specs generating then you want them all with serializable?
> > `quarkus.openapi-generator.codegen.spec.petstore_json.serializableModel=true` seams like an better solution in my opinion :)
> 
> Yes, it's for each spec. I didn't write it there because I was lazy.

Fixed in https://github.com/quarkiverse/quarkus-openapi-generator/pull/907
