### ISSUE TITLE
Missing config generateApi from openapi-generator-maven-plugin

### ISSUE THREAD

**Issue by mbard** [quarkiverse/quarkus-openapi-generator#912]
In the `openapi-generator-maven-plugin`, it is possible to set `generateApi=false` to generate only the models without the API.  

We want to write the API manually but generate the models automatically.  

It would be great if this option were exposed in the configuration as:  

`quarkus.openapi-generator.codegen.spec.<file>.generate_api=false`

**Comment by hbelmiro** [comment]
@mbard this feature was added last week in https://github.com/quarkiverse/quarkus-openapi-generator/pull/897.
